INSERT INTO keyword_topics (kt_name) VALUES ('Topic');
INSERT INTO keywords (k_q, k_title, kt_id, k_added) VALUES ('/g/11g6nkng48', 'Internet outage', (SELECT kt_id FROM keyword_topics WHERE kt_name = 'Topic'), 'now');

INSERT INTO locations (l_name, l_iso) VALUES ('Alabama', 'US-AL');
INSERT INTO locations (l_name, l_iso) VALUES ('Alaska', 'US-AK');
INSERT INTO locations (l_name, l_iso) VALUES ('Arizona', 'US-AZ');
INSERT INTO locations (l_name, l_iso) VALUES ('Arkansas', 'US-AR');
INSERT INTO locations (l_name, l_iso) VALUES ('California', 'US-CA');
INSERT INTO locations (l_name, l_iso) VALUES ('Colorado', 'US-CO');
INSERT INTO locations (l_name, l_iso) VALUES ('Connecticut', 'US-CT');
INSERT INTO locations (l_name, l_iso) VALUES ('Delaware', 'US-DE');
INSERT INTO locations (l_name, l_iso) VALUES ('District of Columbia', 'US-DC');
INSERT INTO locations (l_name, l_iso) VALUES ('Florida', 'US-FL');
INSERT INTO locations (l_name, l_iso) VALUES ('Georgia', 'US-GA');
INSERT INTO locations (l_name, l_iso) VALUES ('Hawaii', 'US-HI');
INSERT INTO locations (l_name, l_iso) VALUES ('Idaho', 'US-ID');
INSERT INTO locations (l_name, l_iso) VALUES ('Illinois', 'US-IL');
INSERT INTO locations (l_name, l_iso) VALUES ('Indiana', 'US-IN');
INSERT INTO locations (l_name, l_iso) VALUES ('Iowa', 'US-IA');
INSERT INTO locations (l_name, l_iso) VALUES ('Kansas', 'US-KS');
INSERT INTO locations (l_name, l_iso) VALUES ('Kentucky', 'US-KY');
INSERT INTO locations (l_name, l_iso) VALUES ('Louisiana', 'US-LA');
INSERT INTO locations (l_name, l_iso) VALUES ('Maine', 'US-ME');
INSERT INTO locations (l_name, l_iso) VALUES ('Maryland', 'US-MD');
INSERT INTO locations (l_name, l_iso) VALUES ('Massachusetts', 'US-MA');
INSERT INTO locations (l_name, l_iso) VALUES ('Michigan', 'US-MI');
INSERT INTO locations (l_name, l_iso) VALUES ('Minnesota', 'US-MN');
INSERT INTO locations (l_name, l_iso) VALUES ('Mississippi', 'US-MS');
INSERT INTO locations (l_name, l_iso) VALUES ('Missouri', 'US-MO');
INSERT INTO locations (l_name, l_iso) VALUES ('Montana', 'US-MT');
INSERT INTO locations (l_name, l_iso) VALUES ('Nebraska', 'US-NE');
INSERT INTO locations (l_name, l_iso) VALUES ('Nevada', 'US-NV');
INSERT INTO locations (l_name, l_iso) VALUES ('New Hampshire', 'US-NH');
INSERT INTO locations (l_name, l_iso) VALUES ('New Jersey', 'US-NJ');
INSERT INTO locations (l_name, l_iso) VALUES ('New Mexico', 'US-NM');
INSERT INTO locations (l_name, l_iso) VALUES ('New York', 'US-NY');
INSERT INTO locations (l_name, l_iso) VALUES ('North Carolina', 'US-NC');
INSERT INTO locations (l_name, l_iso) VALUES ('North Dakota', 'US-ND');
INSERT INTO locations (l_name, l_iso) VALUES ('Ohio', 'US-OH');
INSERT INTO locations (l_name, l_iso) VALUES ('Oklahoma', 'US-OK');
INSERT INTO locations (l_name, l_iso) VALUES ('Oregon', 'US-OR');
INSERT INTO locations (l_name, l_iso) VALUES ('Pennsylvania', 'US-PA');
INSERT INTO locations (l_name, l_iso) VALUES ('Rhode Island', 'US-RI');
INSERT INTO locations (l_name, l_iso) VALUES ('South Carolina', 'US-SC');
INSERT INTO locations (l_name, l_iso) VALUES ('South Dakota', 'US-SD');
INSERT INTO locations (l_name, l_iso) VALUES ('Tennessee', 'US-TN');
INSERT INTO locations (l_name, l_iso) VALUES ('Texas', 'US-TX');
INSERT INTO locations (l_name, l_iso) VALUES ('Utah', 'US-UT');
INSERT INTO locations (l_name, l_iso) VALUES ('Vermont', 'US-VT');
INSERT INTO locations (l_name, l_iso) VALUES ('Virginia', 'US-VA');
INSERT INTO locations (l_name, l_iso) VALUES ('Washington', 'US-WA');
INSERT INTO locations (l_name, l_iso) VALUES ('West Virginia', 'US-WV');
INSERT INTO locations (l_name, l_iso) VALUES ('Wisconsin', 'US-WI');
INSERT INTO locations (l_name, l_iso) VALUES ('Wyoming', 'US-WY');
